discordKey: "discordbotkey"

defaultChannel: "channelname"

blocksToAnnounce:
   - DIAMOND_ORE
   - IRON_ORE
   
delayPerAnnounce: 10

discordCommandPrefix: "!"

discordAddBlockBreakTypeCommand: "addbtype"
discordRemoveBlockBreakTypeCommands: "removebtype"