discordKey: "discordbotkey"

defaultChannel: "channelname"

blocksToAnnounce:
   - DIAMOND_ORE
   - IRON_ORE
   
delayPerAnnounce: 10 # seconds



#########################
#    Coammnd related    #
#########################

discordCommandPrefix: "!"

discordAddBlockBreakTypeCommand: "addbtype"
discordRemoveBlockBreakTypeCommands: "removebtype"

changeDelayPerAnnounce: "delay"